### ISSUE TITLE
 ODS-Component - Dialogs

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#101]
# Dialogs

## Requirement

**As a** developer
**I want** to insert a dialog
**So That** I will get this ready to use component compatible with Orange design specifications and a11y requirements

[DSM reference](https://system.design.orange.com/0c1af118d/p/02ae02-dialogs/b/81772e)

## General description
the mobile App page will propose to the user to describe the component and allow to see the implementation in action.

#### Component
For the component description please refer to the DSM updates

#### App Page
![ScreenShot195](https://user-images.githubusercontent.com/62606284/161217713-02e56e21-132f-40ae-85a4-9e04ee82a980.png)

* title: "Dialogs"
* image: tbd.jpg
* Text: intro text in the DSM
* Core field: The page will propose a mechanism to interact with 
  * A selection of the options available to display the dialogue
    * Checkbox: Title
    * Checkbox: Icon
    * Checkbox: Confirmation dialog - This is not part of the basic component
    * Radio buttons: Action button: 1 - 2
  * A button contained button "Open Dialog" that will launch a dialog with the following:
    * Title: "Dialog Sample"
    * Text: "A dialog box asks the user for further information that the app needs in order to continue. The user has to tap one of the action buttons at the bottom of the box to continue. "
    * Action Buttons: 
      * "Decline" not selected - only closes the dialog
      * "Accept" pre-selected - only closes the dialog

#### Simple Dialog
the default dialogue described above

#### Simple Dialog
-- This version could be added in a second step if too complicated --
* Replace the dialogue text with this: "Dialog boxes can be more complex and include many of the UI components like this: "
* in between the text and the action buttons add the following lines:
  * "Select you configuration:"
  * "Sound" + on/off switch at the end of the line
  * "Magnification"  + on/off switch at the end of the line
  * "Talk Back"  + on/off switch at the end of the line

### States
* NA

### Internationalization
* NA

### Interaction
* All: 
  * The user is able to select a text using the default OS behavior
* Touch: 
  * Nothing Specific
* Keyboard: 
  * Nothing specific

### Animations
* default OS animation

### Visual Accessibility
* taken into account within the design creation process

### Usage Accessibility
* (?) Focus order - NA
* (?) Focus loss expected behavior - NA
* (?) Screen Reader - default OS behavior

## Implementation tasks
- [ ] Task 1
- [ ] Task 2

## Related tasks
- [ ] Task 1
- [ ] Task 2

**Comment by paulinea** [comment]
@B3nz01d For your information, the "confirm" button is mandatory in the SDK so we can't offer the possibility to display it or not.

**Comment by paulinea** [comment]
> @B3nz01d The icon is not a part of the native dialog offered by the SDK. So my question is: am I suppose to develop a custom dialog to handle these two variants: "dialog without confirm button" and "dialog with icon" ?

In fact I found a way to do that easily ;)
