### ISSUE TITLE
 ODS-Component - Floating Action Button

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#109]
# Standard App Bar

## Requirement

**As a** developer
**I want** to insert a FAB
**So That** I will get this ready to use component compatible with Orange design specifications and a11y requirements

[DSM reference](https://system.design.orange.com/0c1af118d/p/577022-buttons-fab/b/101b2a)

#### Component
For the component description please refer to the DSM updates

#### App Page
the page will propose to the user to describe the component and allow to see the implementation in action of the variants.

#### Component
For the component Anatomy please refer to the [DSM description](https://system.design.orange.com/0c1af118d/p/577022-buttons-fab/b/101b2a)

#### App Page
![ScreenShot195](https://user-images.githubusercontent.com/62606284/161217713-02e56e21-132f-40ae-85a4-9e04ee82a980.png)

* title: "Floating Action Button"
* image: TBD
* text: intro text in the DSM   
* variant selection

### Variants
There is only 1 variants:
* Floating Action Button
 

### States
Within the detailed page description, the FAB is positioned in the center of the screen. From the customization Bottom Sheet the use should be able to select
   
* Size: (using choice chips)
  * Default
  * Mini
* "Text (Extended)" - toggle switch -disabled by default and set to disabled for the mini size
  * When text  is on
    * Variable width (full width fab when off)  - toggle switch

### Internationalization
* NA

### Interaction
* All: 
  * The user is able to select a text using the default OS behavior
* Touch: 
  * TBD
* Keyboard: 
  * TBD

### Animations
* TBD

## Accessibility
* the mini version of the component should be using a 48x48dptouch area on top of the 40dp design element

### Visual Accessibility
* taken into account within the design creation process

### Usage Accessibility
* (?) Focus order - NA
* (?) Focus loss expected behavior - NA
* (?) Screen Reader - default OS behavior

**Comment by B3nz01d** [comment]
Pending questions: for @mccart77 : 
* Should we limit the number of characters for the text? In this case, should we use... and what is the number of characters?
* Is it possible to create a FAB with no icon and just text?
* Should we implement the transformation from standard to extended FAB (example showing transition on scrolling to top of the list)?
* Is it possible to create a full width extended FAB?
* should we show an example of an expanding FAB that switches from an icon to an icon + text when positioned specifically?

**Comment by B3nz01d** [comment]
* The text of an extended tab should never be truncated - the code should not limit the number of characters - the DSM should be updated with a max number of characters
* Is it possible to create a FAB with no icon and just text, but in Orange we should always use a Solaris icon. the code should not force user to have the icon as mandatory. We do not need to show this example in the demo app
* Is it possible to create a full width extended FAB? yes
*

**Comment by B3nz01d** [comment]
@mccart77  is raising the question of the placement and to see if we should include multiple examples.
Decision was made to push the animations and position example in a latter version

**Comment by B3nz01d** [comment]
@mccart77  is raising the question of the placement and to see if we should include multiple examples.
Decision was made to push the animations and position example in a latter version

**Comment by paulinea** [comment]
@mccart77 @B3nz01d I think illustration for the floating action buttons is missing. I didn't find it in the One Drive zip file. We also need the generic version in back & white. So this issue is not really ready to dev ;) My bad cause I forget to ask for these resources.
