### ISSUE TITLE
 ODS-Component - Banners

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#115]
# Banners
## Requirement

**As a** developer
**I want** to insert a banner in a page
**So That** I will get this ready to use component compatible with Orange design specifications and a11y requirements

[DSM reference]() (To be updated)

#### Component
For the component description please refer to the staging DSM

#### App Page
the page will propose to the user to describe the component and allow to see variants implementation in action.

### User Experience
* a new card is added in the component list
* when the user taps on the card the component page is opened
* In the variants list when the user taps on the Banner demo the demo page is opened

#### Component Page
* Header:
  * title: "Banners"
  * back link: to components list page
  * Action icon: none
* image: xxx.jpg
* Text: intro text  description in the DSM
* Variant link list:
  * "Banners Demo" 

#### Variant Demo Page
* Header:
 * title: "Banners"
 * back link: to Banners description page
 * Action icon: none
* Implementation example
 * a banner example is shown in the page
* Customization bottom sheet
 * "text" : using choice chips 
   * "short"
   * "long"
 * "button" : using choice chips 
   * "side"
   * "under"

### States
* NA

### Internationalization
* NA

### Interaction
* All: 
  * 
* Touch: 
  * Nothing Specific
* Keyboard: 
  * Nothing specific

### Animations
* NA

### Visual Accessibility
* taken into account within the design creation process

### Usage Accessibility
* (?) Focus order - NA
* (?) Focus loss expected behavior - NA
* (?) Screen Reader - default OS behavior
* (?) Switch Control

## Technical specifications
https://m2.material.io/components/banners

**Comment by B3nz01d** [comment]
@paulinea  I do not see this component in today's version

**Comment by paulinea** [comment]
@B3nz01d Try again cause it has been delivered :D
