### ISSUE TITLE
[Bug]: About page Horizontal behavior issue

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#132]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

multiple devices

### OS Version

multiple OS

### App version

v1.0.1

### Describe the issue

go on the About page > switch the device to horizontal 
* On one Galaxy S10 (Android 9) & Galaxy A3 (Android 8) > the screen moves to horizontal on the guideline page
* On Pixel 2  (Android 11), Sony Xperia XZ3  (Android 10) & Huawei Mate20 Pro (Android 10) > the screen re-arranged in horizontal but switched automatically from light to dark

Same behavior was found in the Typograpgy & Color page 

### Expected Behavior

the horizontal page should stay on the About page

**Comment by paulinea** [comment]
@B3nz01d Could you check if the last version delivered on App Tester fix this bug cause I refactored many things and on my side I don't reproduce this issue.

**Comment by B3nz01d** [comment]
* Galaxy S10 (Android 9): horizontal switch stays on about page
* Galaxy A3 (Android 8):  horizontal switch stays on about page
* Pixel 2 (Android 11): horizontal switch is ok and light and dark stays
* Sony Xperia XZ3 (Android 10):  horizontal switch is ok and light and dark stays
* Huawei Mate20 Pro (Android 10): horizontal switch is ok and light and dark stays
