### ISSUE TITLE
[Bug]: Card Horizontal

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#135]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

any

### OS Version

any

### App version

1.0.1

### Describe the issue

When switching the screen to horizontal the full card is not visible as the buttons do not show therefore the card is not completely visible

### Expected Behavior

the scroll should be available to see the bottom of the card

**Comment by paulinea** [comment]
@B3nz01d I think I fixed this issue in my refactoring, could you check?

**Comment by B3nz01d** [comment]
tested today and it's good now
