### ISSUE TITLE
Bug - Lists new variants

### ISSUE THREAD

**Issue by mccart77** [Orange-OpenSource/ods-android#141]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

Samsung Galaxy A51 5G

### OS Version

Android 11

### App version

v1.0 (1)

### Describe the issue

Additional variants have been designed and specified and are not included in the Lists displayed. This includes single line, two line and three line lists.

Updated design reference: https://system.design.orange.com/0c1af118d/p/09a804-lists/b/669743

### Expected Behavior

Lists section will include all new and updated list variants as specified in the DSM:

https://system.design.orange.com/0c1af118d/p/09a804-lists/b/669743

**Comment by florentmaitre** [comment]
@mccart77 Should we follow this design ?https://app.zeplin.io/project/621f9736756b8eab5a1d1ca1/screen/628361a24510e4169825b9d6

**Comment by B3nz01d** [comment]
Identified corrections:
- [ ] the text  for the list item size needs to be updated with plural: "1 line - 2 line**s** - 3 line**s**"
- [ ] the chips are not using the right outline formats that you can see on the other bottom sheets

**Comment by paulinea** [comment]
New bug created for wording issue: #252
For the outlined chips, we have to wait for #169 merge
