### ISSUE TITLE
Bug - contrôle enable-disabled clarification 

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#173]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

Any

### OS Version

Any

### App version

V0. 3

### Describe the issue

All selector items have the same name

![Screenshot_20220612_143024](https://user-images.githubusercontent.com/62606284/173234698-e07becea-4c40-4523-9b67-483e8ad3b440.jpg)

![Screenshot_20220612_143513](https://user-images.githubusercontent.com/62606284/173234705-8cfa3484-f433-4f36-8b96-b3a9dd20c9a7.jpg)

![Screenshot_20220612_143602](https://user-images.githubusercontent.com/62606284/173234928-794d23ce-553d-434b-8e76-717944c75a39.jpg)

### Expected Behavior
Checkbox
* enabled Checkboxes : 3 choices one under the other, where the user can select more then one item
  * Item 1 (Selected)
  * Item 2 
  * Item 3 (Select)
* disables Checkboxes : 3 choices one under the other
  * Item 1  (Selected)
  * Item 2
  * Item 3  (Selected)

Radio Buttons
* enabled Radio buttons: 3 radio buttons choices one under the other, where the user can only select one
  * Item 1 (Selected)
  * Item 2
  * Item 3
* disables radio buttons: 3 radio buttons choices one under the other
  * Item 1  (Selected)
  * Item 2
  * Item 3

Switches 
* enabled 
  * item 1 (shows the switch where the user can activate or not)
* disabled:
  * Item 1  (Selected)
  * Item 2

**Comment by B3nz01d** [comment]
I do not see the request performed as described in parapgraph  expected behavior

**Comment by afrahB** [comment]
Bug Accessibility : Dans checkBox Les cases à cocher ne sont pas vocalisés par Talkback.
-> vérifier la vocalisation des items dans Checkbox
