### ISSUE TITLE
[Bug]: Activity indicator centered

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#202]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

any

### OS Version

any

### App version

v0.3.0  (144)

### Describe the issue

Position of the example is left aligned and should be centre aligned
<img src="https://user-images.githubusercontent.com/62606284/176430385-3446bd2d-097c-491b-b9e1-607950c4e631.jpg" width=300>

### Expected Behavior

Position of the example is left aligned and should be centre aligned

**Comment by B3nz01d** [comment]
@mccart77 I've added this task to be consistant with the iOS request https://github.com/Orange-OpenSource/ods-ios/issues/101

**Comment by florentmaitre** [comment]
@B3nz01d Should we also center progress bars ? Or expand them on the entire line ?

![Screenshot_20220629_181745](https://user-images.githubusercontent.com/13621389/176486102-0e2671d3-ec60-4180-8b7e-9d972b275579.png)
