### ISSUE TITLE
Update the Text Fields page

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#221]
# Text Fields

## Requirement

**As a** developer reviewing the mobile demo app
**I want** to be able to use the demo app
**So That** it reflects the various text fields options available

## General description
- The following variants should be added in and be editable: _(To Be Checked with Android)_
  - [ ] Text Field
  - [ ] Secure Field
  - [ ] Text Editor (multiline)
  - [ ] Text Input Autocapitalization

**Comment by paulinea** [comment]
@B3nz01d We have to clarify this issue cause text selection is not a text field. Not very clear for us.

**Comment by B3nz01d** [comment]
About the DSM Text field page: https://system.design.orange.com/0c1af118d/p/483f94-text-fields/

We have gathered the following clarifications based on the latest DSM updates:
*  the technical level of the jetpack library is providing 2 separate functions that either show the filled text field and the outlined text field. Therefore we need to keep this first level clearly visible for the developers. 
* With the need to show filled or outlined AND text/secured/multiple lines we proposed the following structure for the new dev:
  * Filled 
    *  text fields : options for the bottom sheet
      * tab text field: 
        * Input Type: Single line / Multi line / Text Area 
        * State: Default / Error / Disabled
        * Leading icon: Toggle
        * Trailing: None / Icon / Text
        * Character Counter: Toggle
      * tab keyboard options: 
        * type: text / Number / Decimal / Phone / Url / Email  
        * Capitalization: toggle
        * Action: None / Default / Go / Search / Send / Previous / Next / Done
    *  Password filed : options for the bottom sheet: 
       * State : Default / Error / Disabled
       * Text password / number password
       * Trailing Visualization icon
       * Keyboard: Text Password / Number Password
  * Outlined text field
    * text fields - same as previously described
    * Password filed - same as previously described

![image](https://user-images.githubusercontent.com/62606284/186147526-0f32ad37-d779-4523-93a5-5abe6c078135.png)


@mccart77 we have looked at this request and have found the following question:
* In the DSM we see that there is the option of showing or hiding the label in the fields. Right now and by default in android jetpack the label is always visible. Do we need to show an example of the label hidden or do you consider that the design should always show a label?
