### ISSUE TITLE
Bug - Guideline and component images are cropped

### ISSUE THREAD

**Issue by florentmaitre** [Orange-OpenSource/ods-android#229]
This is clearly visible with the typography image:

![Screenshot_20220726_153841](https://user-images.githubusercontent.com/13621389/181019939-e6d6d677-86ec-4513-807e-11ad2708876d.png)

Whereas resource is:

![il_typography](https://user-images.githubusercontent.com/13621389/180749106-4ec6c268-19ba-4270-aaca-0d4d603c556e.png)

**Comment by florentmaitre** [comment]
As we can't predict the device screen ratio, the solution we applied on this issue is to make every image fit into the rectangle (without modifying the image ratio obviously), and then apply a dark color (the same as the one in the image backgrounds) to fill the gaps.

There are several exceptions to this rule :
- The guideline color image can be vertically stretched without modifying the content, so we don't have any gap to fill.
- Some images need to be stacked on one side of the rectangle they fit in. For instance, the bottom navigation image is stacked at the top of the rectangle, the lists image is stacked at the bottom and sliders as well as progress images are stacked on the left (for sliders and progress this is not visible on the screenshot below, but this might happen on other screens).

Here are some screenshots of the guidelines and components screens, with the gaps filled with a blue color so that you can see them:

- Guidelines:

![1](https://user-images.githubusercontent.com/13621389/181023462-710637f0-f889-4f45-a427-ddcf5fcd4065.png)

- Components:

![4full](https://user-images.githubusercontent.com/13621389/181024284-81e50621-fd12-4b65-b2ab-079d8cb05032.png)

- Component details: 

![2](https://user-images.githubusercontent.com/13621389/181023546-d39f523e-efe7-49f1-91e7-080e32a9caf6.png)

![3](https://user-images.githubusercontent.com/13621389/181023555-9e912c36-9ee6-48bb-8f60-e1381f9916b7.png)

**Comment by B3nz01d** [comment]
test OK
