### ISSUE TITLE
[Bug]:  Add vocalisation for selected button in icon (in Scrollable tabs)

### ISSUE THREAD

**Issue by afrahB** [Orange-OpenSource/ods-android#280]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

Samsung S20

### OS Version

Android 11

### App version

1.0

### Describe the issue

in Scrollable tabs : the state (clicked or not) for the position of the icon in "click to customize" is not vocalized.

### Expected Behavior

Add a vocalisation about the state of the button.

**Comment by afrahB** [comment]
I still have the same bug : the position selected for the icon is not vocalised.

**Comment by paulinea** [comment]
I created a new issue for Android 10 vocalization: #372
