### ISSUE TITLE
Update the Button's demo page with a customization bottom sheet 

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#303]
The target is to show the existing variants as already used with link to related page demo structured as follows:

* each page would show the standard, the forced on light and the forced on dark examples
* with a customization bottom sheet to allow:
  * "icon" - toggle switched off
  * "variable width" - toggle switched off
  * "disabled" - toggle switched off

On the Toggle buttons example another customization should be added:
* Toggle count - step counter from 1-3

**Comment by paulinea** [comment]
@mccart77 @B3nz01d I didn't found the toggle buttons in disabled state in the DSM. For the moment I submit this PR like that but there is a missing case.
