### ISSUE TITLE
ODS-Component - Card -  horizontal card

### ISSUE THREAD

**Issue by paulinea** [Orange-OpenSource/ods-android#35]
# Card with Image side by side with the Text

The content of this task is described in #17

Note the the divider can be taked out, by default there is one.

**Comment by B3nz01d** [comment]
@mccart77  when no text is shown should the available text be centered vertically?

**Comment by mccart77** [comment]
> @mccart77 when no text is shown should the available text be centered vertically?

as discussed earlier, yes, vertically centrally aligned.
