### ISSUE TITLE
[Bug]: Text field > password > visual icon deselection action

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#376]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

any

### OS Version

any

### App version

v0.8 (60)

### Describe the issue

As a user of the mobile app
* when you test the password field
* then you type in text
* then you click on the visualition icon to see your text
* then you deselect the "visualization icon" option
* as a result you still see the content of you text

### Expected Behavior

when deselecting and therefore taking away the visualization option the content of the password field should be using the dote to hide the content of the field

**Comment by paulinea** [comment]
@B3nz01d On which OS version did you see this problem? On my mobile it is ok.
