### ISSUE TITLE
Define format for Demo Data file for food content

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#385]
**As a user** of the demo App 
**I want** to see the the components demonstration
**So that** there is real content in the components

In order to build this content we should use a common file to use to build the content in the demo app.

The json format should be used

The objective of this task is to build a common file between android and iOS to use in the demo app.

Corresponding task in iOS: https://github.com/Orange-OpenSource/ods-ios/issues/315

**Comment by paulinea** [comment]
We used the provided format and it works ;)
