### ISSUE TITLE
[Bug Accessibility]: Bug Vocalisation when user click on "report an issue " in "About" section

### ISSUE THREAD

**Issue by afrahB** [Orange-OpenSource/ods-android#422]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

Samsung A53

### OS Version

Android 11

### App version

1.0

### Describe the issue

Go to -> About
Activate Talkback
Go to "report an issue"

Talkback vocalise at first the field "Username or email adress"

### Expected Behavior

Talkback should vocalise the title of the page : Sign in on Github

**Comment by paulinea** [comment]
@afrahB This issue is not on our hand cause on our side this is a simple link which open the GitHub page.

**Comment by paulinea** [comment]
This issue is not on our hand cause on our side this is a simple link which open the GitHub page.
