### ISSUE TITLE
[Bug Accessibility]  vocalise the content change in bottom sheet

### ISSUE THREAD

**Issue by afrahB** [Orange-OpenSource/ods-android#442]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

Samsung A53

### OS Version

Android 11

### App version

1.0

### Describe the issue

Activate Talkback
Go to sheets : bottom
Activate example 
when user click on "recipes" to show/close the bottom sheet : there is no vocalisation 

### Expected Behavior

Vocalise correctly the content change

**Comment by florentmaitre** [comment]
@afrahB Talkback currently says "Collpased" or "Expanded" when user clicks on "Recipes". Should we also vocalize the title of the bottom sheet ? (that would result in "Recipes, collapsed" or "Recipes, expanded").
