### ISSUE TITLE
 ODS-Component - Image Item

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#473]
# Component: Image Item

## Requirement

**As a** developer
**I want** to insert an Image Item
**So That** I will get this ready to use component compatible with Orange design specifications and a11y requirements

#### Component
For the component description please refer to the [DSM description](https://system.design.orange.com/0c1af118d/p/03eab7-image-lists/b/66c290)

#### App Page
the page will propose to the user to describe the component and allow to see the implementation in action of the variants.

#### Component
For the component Anatomy please refer to the [DSM description](https://system.design.orange.com/0c1af118d/p/577022-buttons-fab/b/101b2a)

#### App Page

* title: "Image item"
* image: TBD
* text: intro text in the DSM   (In absence of the final text use: "The Image item component is the individual image display used in the Image list module, and it allows to display image lists or media categories")
* variant selection

### Variants
Here are the following variants, answering to the following customizations:
* text (toggle switch defaulted to on) when the text is displayed it is always with an overlay
* icon  (toggle switch defaulted to off) when the heart icon is shown it is displayed with an outline and the user can tap on it to set it to on with an filled icon - on next tap it's set back to off, as outline
 

### Internationalization
* NA

### Interaction
* All: 
  * The user is able to select a text using the default OS behavior
* Touch: 
  * TBD
* Keyboard: 
  * TBD

### Animations
* TBD

## Accessibility
* TBD

### Visual Accessibility
* taken into account within the design creation process

### Usage Accessibility
* (?) Focus order - NA
* (?) Focus loss ex
* pected behavior - NA
* (?) Screen Reader - default OS behavior

**Comment by paulinea** [comment]
@B3nz01d What are the possible customizations for the component?
@ChristineKuster We need the illustration to display in the component list and its variant in black & white.

**Comment by paulinea** [comment]
@mccart77 What should be the description for this component?
