### ISSUE TITLE
Toggle button example Update

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#483]
As a user of the demo app
I want to see the example implementaion
So that I can understand the toogle switch behavior

The example should show 3 icones one next to each other with the normal toggle switch behavior: Only one of them can be selected.

**Comment by paulinea** [comment]
@B3nz01d Are you sure this is always the behavior of toggle button? During the design meeting, we talked about the case of "bold", italic", "underlined".
We could add a customization switch called "exclusive selection" or something like that.

**Comment by paulinea** [comment]
@B3nz01d I think this has been developed like that in previous sprint. Could you test and confirm this works as expected?

**Comment by B3nz01d** [comment]
this has been corrected in the latest release
