### ISSUE TITLE
Update the icon buttons

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#484]
Today we have the following buttons:
* Highest emphasis buttons
* High emphasis buttons
* Medium emphasis buttons
* Low buttons
* Functional buttons
* Toggle buttons
* Icon buttons

The objective is to build the following:
* Buttons (only keeps the following items):
  * Highest emphasis buttons
  * High emphasis buttons
  * Medium emphasis buttons
  * Low buttons
  * Functional buttons
* Buttons: icons (New component with the following items)
  * Outline icon buttons
  * Standard Icon buttons
    * 2 states are possible with or without toggle (in the customization bottom sheet: Toggle  using a switch for user selection)
  * Group Toggle button (the behavior is that you can select 0, 1, on more at a time)

**Comment by paulinea** [comment]
@B3nz01d @ChristineKuster We need an illustration for the "Buttons: icons" component for Orange and generic theme (black & white)
