### ISSUE TITLE
List the libraries use for the creation of the demo app

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#485]
**As a User** of the demo app
**I want** to know the denpencies of the app
**So that** I have a list of all the libraries used in the app

What needs to be provided:
- The list of the libraries used to build the app
- The list of libraries used by the ODS code library
- For each library identify the license associated to it

**Comment by florentmaitre** [comment]
There is already a [THIRD_PARTY.txt](https://raw.githubusercontent.com/Orange-OpenSource/ods-android/develop/THIRD_PARTY.txt) file in the repository. I suppose you want to display this in the app too?

**Comment by paulinea** [comment]
This could be good to finalize this issue before the v1 @B3nz01d, what do you think?

**Comment by paulinea** [comment]
> @paulinea I understand the list provided in the about > "Third party library" contains all the libs used by the demo app. Where would the list of the lib itself's dependency be available?

This list includes the dependencies used by the library.

**Comment by B3nz01d** [comment]
@paulinea is it possible to isolate in this file ODS lib dependencies from the demo app dependencies?

**Comment by paulinea** [comment]
@B3nz01d Yes but we have to define how. Some libraries are used for the demo app and for the lib so we will have redundant things.

**Comment by B3nz01d** [comment]
I propose this format and list the lib first and then the full app list (redundancy is ok, just make sure that transitive redundancies are not necessary):

## In the ODS Lib
Material Components
Copyright 2017 The Android Open Source Project
https://github.com/material-components/material-components-android
Apache License 2.0

Coil
Copyright 2023 Coil Contributors
https://github.com/coil-kt/coil
Apache License 2.0


## In the app
Copyright 2020 The Android Open Source Project
https://github.com/google/accompanist
Apache License 2.0

AndroidX
Copyright 2021 The Android Open Source Project
https://github.com/androidx/androidx
Apache License 2.0

Coil
Copyright 2023 Coil Contributors
https://github.com/coil-kt/coil
Apache License 2.0

Dagger
Copyright 2012 The Dagger Authors
https://github.com/google/dagger
Apache License 2.0

Firebase
Copyright 2019 Google LLC
https://github.com/firebase/firebase-android-sdk
Apache License 2.0

Google services
Copyright (C) 2023 The Android Open Source Project
https://github.com/google/play-services-plugins/tree/master/google-services-plugin
Apache License 2.0

JUnit
https://github.com/junit-team/junit5/
Eclipse Public License 2.0

KotlinPoet
Copyright 2017 Square, Inc.
https://github.com/square/kotlinpoet
Apache License 2.0

Kotlin Symbol Processing
https://github.com/google/ksp
Apache License 2.0

Material Components
Copyright 2017 The Android Open Source Project
https://github.com/material-components/material-components-android
Apache License 2.0

ODS libraries
Copyright (c) Orange SA
https://github.com/Orange-OpenSource/ods-android
MIT License

Roboto fonts
https://fonts.google.com/specimen/Roboto
Apache License 2.0

Timber
Copyright 2013 Jake Wharton
https://github.com/JakeWharton/timber
Apache License 2.0
