### ISSUE TITLE
[Accessibility]: Vocalisation of the result in Search Page

### ISSUE THREAD

**Issue by afrahB** [Orange-OpenSource/ods-android#506]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

Samsung A53

### OS Version

Android 11

### App version

1.0

### Describe the issue

Talkback activated
When the user types an item in the search field
no vocalization of the result 

### Expected Behavior

Vocalize the number of elements found in the result

**Comment by paulinea** [comment]
@afrahB Vocalization is ok on my S22 with Android 13. Talkback announces the number of results.
