### ISSUE TITLE
XML - Component - Navigation Bar

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#526]

**Comment by B3nz01d** [comment]
@paulinea  should the xml code be visible in the xml code panel, as I do not see it?

**Comment by paulinea** [comment]
> @paulinea should the xml code be visible in the xml code panel, as I do not see it?

@B3nz01d The XML code implementation of the bottom navigation has been added in the [#671](https://github.com/Orange-OpenSource/ods-android/issues/671) which has not been merged for the moment.
