### ISSUE TITLE
XML - Component - Buttons Outlined and Contained

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#528]

**Comment by B3nz01d** [comment]
@paulinea  what needs to be tested?

**Comment by paulinea** [comment]
@B3nz01d The XML version of these components by switching the code implementation dropdown menu.

**Comment by B3nz01d** [comment]
issues have been found in this xml implementation when forcing the dark mode. bug created in #656

**Comment by B3nz01d** [comment]
@paulinea  should the xml code be visible in the xml code panel, as I do not see it?

**Comment by paulinea** [comment]
> @paulinea should the xml code be visible in the xml code panel, as I do not see it?

@B3nz01d This has not been added for this component. XML code implementation has been developed for the bottom navigation but the PR has not been merged yet.
