### ISSUE TITLE
Update the Placeholder image

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#531]
## Requirement
*As a User* of the library
*I Want* to lad images
*So That* there is:
* a placeholder image when loading the image
* a placehodler error image when there is an error in loading the image
* a placeholder image adapted for ligh and dark mode

## General description
New images have been provided for placeholder images using the solaris icon. These new images need to be used to replace the existing ones.

**Comment by florentmaitre** [comment]
We already have `placeholder.png`, `placeholder_error.png` and `placeholder_dark.png` image resources in the demo app and we can make them available in the library.

However it would be better to have vector images.

**Comment by ChristineKuster** [comment]
@paulinea Hi Pauline, I don't know what is it about ! We can talk about during the Android meeting of wednesday
