### ISSUE TITLE
Search - Add typography tokens in search result

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#551]
*As a User* of the demo app
*I can* search for the typography tokens
*So That* I can get access the the dedicated typography description

Complementary description:
* Each typography token should be available.
* Each item should link back to the typography page on the dedicated paragraph (as an anchor)
* This task is linked to the task #550 to make sure the old token Os and the new tokens are both available

**Comment by paulinea** [comment]
@B3nz01d which image do we have to display in search results for typography elements?
