### ISSUE TITLE
illustration alignement

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#618]
The illustration is right aligned instead of centered for the text field and the slider in: 
* the small car of the component 
* and in the illustration of the description page

for the following components:
* sliders
* text fields

<img src="https://github.com/Orange-OpenSource/ods-android/assets/62606284/b322b2d4-8929-4186-a42b-66f39e67468d" width="300">

<img src="https://github.com/Orange-OpenSource/ods-android/assets/62606284/9e1d448e-1f94-4404-b465-dfed173593d9" width="300">

<img src="https://github.com/Orange-OpenSource/ods-android/assets/62606284/8eb77fda-39ae-48fb-b071-1f127600a078" width="600">

**Comment by paulinea** [comment]
@B3nz01d The design provided us illustrations which are right aligned so in portrait mode, the image are aligned to the right and it is normal (or the images have to be modified by the design). I can only center the images in landscape mode. Is it ok for you?
