### ISSUE TITLE
Navigation drawer placeholder illustration alignment

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#619]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-android/issues) for duplicate or closed feature requests

### Your test device

Any

### OS Version

Any

### App version

v0.14 (b237)

### Describe the issue

The illustration element does not seem to be vertically centered

<img src="https://github.com/Orange-OpenSource/ods-android/assets/62606284/18cbdf13-1aab-4106-8730-c61203b1408a" width="300">

### Expected Behavior

the placeholder image should be centered horizontally and vertically

**Comment by paulinea** [comment]
@B3nz01d This is because the placeholder takes the place of the image. The title ("Side navigation title" here) layer is displayed as an overlay over this image.
