### ISSUE TITLE
[Bug]: Error 404 after clicking on "ODS

### ISSUE THREAD

**Issue by StefAdam** [Orange-OpenSource/ods-android#629]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-android/issues) for duplicate or closed feature requests

### Your test device

MacBook Pro M1Pro

### OS Version

Ventura 13.1

### App version

Didn't see any version #

### Describe the issue

On this page : https://system.design.orange.com/0c1af118d/p/052851-ods-android-library/b/459844
In the Links tab
When I click on ODS Android tile,
I am directed to a 404 error page

### Expected Behavior

I suppose it should link to a landing page for ODS Android documentation

**Comment by paulinea** [comment]
It has been fixed by the last release. The link is working again!
