### ISSUE TITLE
[Bug]: OdsTextField practically not usable as sizing or positioning constraints are not honored

### ISSUE THREAD

**Issue by LaurentRenard** [Orange-OpenSource/ods-android#635]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-android/issues) for duplicate or closed feature requests

### Your test device

Pixel 3 XL (whatever)

### OS Version

Android 12 (any)

### App version

0.15 (and previous)

### Describe the issue

The implementation of OdsTextField prevent it to be used in a composition as another composable, as sizing or positioning constraints are not honored.
Examples:

```kotlin
@Preview(showBackground = true)
@Composable
fun SizingNotHonoredPreview() {
    OdsTheme(themeConfiguration = OrangeThemeConfiguration()) {
        Row {
            OdsTextField(
                modifier = Modifier.weight(1F),
                value = "Hey, my width is constrained to half of the screen",
                onValueChange = {}
            )
            OdsTextBody1(modifier = Modifier.weight(1F), text = "..., but you cannot see me!")
        }
    }
}

@Preview(showBackground = true, device = "spec:parent=pixel_5,orientation=landscape")
@Composable
fun PositionNotHonoredPreview() {
    OdsTheme(themeConfiguration = OrangeThemeConfiguration()) {
        Box(modifier = Modifier.fillMaxSize()) {
            OdsTextField(
                modifier = Modifier.align(BottomEnd),
                value = "I could have been at the bottom end, but I'm not",
                onValueChange = {}
            )
        }
    }
}
```

Indeed, in the implementation, no constraint from the modifier has been transferred to the root composable (a Column) 

### Expected Behavior

OdsTextField should honor sizing and positioning constraints passed to its modifier

**Comment by B3nz01d** [comment]
@paulinea  how can this be tested?

**Comment by paulinea** [comment]
@B3nz01d You can't, this is linked to a usage of the component by code...

**Comment by LaurentRenard** [comment]
Can't find a way to re-open the issue, but the fix was not applied to `OdsPasswordTextField`, which cannot be constrained by the caller as well.

**Comment by paulinea** [comment]
> Can't find a way to re-open the issue, but the fix was not applied to `OdsPasswordTextField`, which cannot be constrained by the caller as well.

Sorry, I missed it. I'll fix that quickly!
