### ISSUE TITLE
Documentation - Add tables to explain API parameters

### ISSUE THREAD

**Issue by paulinea** [Orange-OpenSource/ods-android#638]
Add a table in markdown file can  be done as follow:

```markdown
Parameters | Descriptions
-- | --
`message: String` | Text to be displayed into the banner
`firstButton: OdsBannerButton` | Principal button to be displayed in the banner
`modifier: Modifier` | `Modifier` to be applied to the banner
`image: OdsBannerImage?` | Image to be displayed in the banner in a circle shape
`secondButton: OdsBannerButton?` | Secondary button to be displayed in the banner
{:.table}
```

Where `{:.table}` allows to apply Boosted table style.

**Comment by B3nz01d** [comment]
I cannot test this yet right?
I do not see tables in the current exposed doc

**Comment by paulinea** [comment]
@B3nz01d I sent you the link to test by Teams several days ago: [https://deploy-preview-658--ods-android.netlify.app/components/buttons_docs](https://deploy-preview-658--ods-android.netlify.app/components/buttons_docs )
