### ISSUE TITLE
[Bug]: Back button missing in about sub pages

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#702]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-android/issues) for duplicate or closed feature requests

### Your test device

Any

### OS Version

Any

### App version

v0.17.0 (302)

### Describe the issue

When you go in:
About > Any sub item
The back button and the header are missing

### Expected Behavior

put it back ;)

**Comment by paulinea** [comment]
It will be fixed by About Module branch (#19) merging
