### ISSUE TITLE
Doc - GitHub about information

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ods-android#8]
### Documentation Location

Not really in the documentation but rather [in the GitHub repository](https://github.com/Orange-OpenSource/ods-android).

### Current issue

The text in the "About" section is written in French and should be in English.

<img width="263" alt="Capture d’écran 2022-02-10 à 10 20 33" src="https://user-images.githubusercontent.com/17381666/153376592-eee459f5-b9e0-4668-9ad2-fc0048e9d24f.png">

**Comment by julien-deramond** [comment]
I don't have the rights to modify it so I'm unassigning it to me.

**Comment by B3nz01d** [comment]
could you update the text to: 
"Reusable Android graphical components library to apply the Orange Design System (ODS)."
