### ISSUE TITLE
Typography and colors documentation update

### ISSUE THREAD

**Issue by paulinea** [Orange-OpenSource/ods-android#818]
The typography and the colors sections of the documentation are obsolete.

**Comment by B3nz01d** [comment]
@paulinea  is this available for test? and where?

**Comment by paulinea** [comment]
> @paulinea is this available for test? and where?

@B3nz01d 
Colors: https://orange-opensource.github.io/ods-android/guidelines/Colors_docs
Typography: https://orange-opensource.github.io/ods-android/guidelines/Typography_docs
