### ISSUE TITLE
Bug - Impossible to go to "Components": Crash

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ods-android#98]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

Samsung - Galaxy A5 (2016) - SM-A510F

### OS Version

Android 7.0

### App version

1.0 (1) Last merged PR: 20-ods-component-bottom-navigation

### Describe the issue

Going to "Guidelines", "Modules" and "About" works perfectly. Switching light/dark modes as well.
But when I go to "Components", the application crashes.

### Expected Behavior

Be able to see the content of the "Components" page.

**Comment by B3nz01d** [comment]
I have the same issue on galaxy S6 on Android 8

**Comment by B3nz01d** [comment]
Tested again with version 0.3-c386f7f
* on galaxy S6: stil got a crash
* on galaxy A3: OK

**Comment by florentmaitre** [comment]
Related Google issue: https://issuetracker.google.com/issues/230166331

**Comment by B3nz01d** [comment]
it works for me

**Comment by B3nz01d** [comment]
@julien-deramond cannot test on the device where the bug was identified
